openapi: 3.0.1
info:
  description: "OAS 3.0.1 definition of the NS Provisioning MnS Â© 2022, 3GPP Organizational\
    \ Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC). All rights reserved."
  title: NSS Provisioning MnS
  version: 17.6.0
externalDocs:
  description: 3GPP TS 28.531; Management and orchestration; Provisioning
  url: http://www.3gpp.org/ftp/Specs/archive/28_series/28.531/
servers:
- url: "{MnSRoot}/NSSProvMnS/{MnSVersion}/SliceSubnetMgmt"
  variables:
    MnSRoot:
      default: http://example.com/3GPPManagement
      description: See clause 4.4.2 of TS 32.158
    MnSVersion:
      default: XXX
      description: Version number of the OpenAPI definition
paths:
  /SliceProfile:
    post:
      description: With HTTP POST a complete Slice Profile is created if it does not
        exist.
      operationId: allocate_nssi
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SliceProfile'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SliceProfile'
          description: Success case ("201 Created"). This status code shall be returned
            when the resource is created. The representation of the created resource
            is returned in the response message body.
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error case.
      summary: "to allocate a network slice subnet instance provided by the service\
        \ provider, the network slice subnet instance may be new or existing"
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /SliceProfile/{sliceProfileId}:
    delete:
      description: With HTTP DELETE one resource is deleted. The resources to be deleted
        is identified with the target URI.
      operationId: deallocate_nssi
      parameters:
      - explode: false
        in: path
        name: sliceProfileId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: "Success case (\"200 OK\"). This status code is returned, when\
            \ the resource has been successfully deleted. The response body is empty."
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error case.
      summary: Deallocates a Network Slice Subnet
      x-openapi-router-controller: openapi_server.controllers.default_controller
    get:
      description: With HTTP GET resources are read. The resources to be retrieved
        are identified with the target URI. The attributes and fields parameter of
        the query components allow to select the resource properties to be returned.
      operationId: get_nssi
      parameters:
      - explode: false
        in: path
        name: sliceProfileId
        required: true
        schema:
          type: string
        style: simple
      - description: This parameter extends the set of targeted resources beyond the
          base resource identified with the path component of the URI. No scoping
          mechanism is specified in the present document.
        explode: true
        in: query
        name: scope
        required: false
        schema:
          $ref: '#/components/schemas/Scope'
        style: form
      - description: This parameter reduces the targeted set of resources by applying
          a filter to the scoped set of resource representations. Only resource representations
          for which the filter construct evaluates to "true" are targeted. No filter
          language is specified in the present document.
        explode: true
        in: query
        name: filter
        required: false
        schema:
          $ref: '#/components/schemas/Filter'
        style: form
      - description: This parameter specifies the attributes of the scoped resources
          that are returned.
        explode: false
        in: query
        name: attributes
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      - description: This parameter specifies the attribute field of the scoped resources
          that are returned.
        explode: false
        in: query
        name: fields
        required: false
        schema:
          items:
            type: string
          type: array
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SliceProfile'
          description: "Success case (\"200 OK\"). The resources identified in the\
            \ request for retrieval are returned in the response message body. In\
            \ case the attributes or fields query parameters are used, only the selected\
            \ attributes or sub-attributes are returned. The response message body\
            \ is constructed according to the hierarchical response construction method\
            \ (TS 32.158 [15])."
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
          description: Error case.
      summary: Reads Slice Profile information
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    ScopeType:
      enum:
      - BASE_ONLY
      - BASE_NTH_LEVEL
      - BASE_SUBTREE
      - BASE_ALL
      title: ScopeType
      type: string
    Operation:
      enum:
      - add
      - remove
      - replace
      type: string
    Insert:
      enum:
      - before
      - after
      type: string
    Scope:
      properties:
        scopeType:
          $ref: '#/components/schemas/ScopeType'
        scopeLevel:
          type: integer
      type: object
    SliceProfile:
      example:
        rANSliceSubnetProfile:
          synchronicity:
            accuracy: 2.027123
            availability: null
          uLThptPerSliceSubnet:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            guaThpt: 5.637377
            maxThpt: 2.302136
          survivalTime: 3.5571952270680973
          reliability: 5.025004791520295
          uESpeed: 4
          energyEfficiency: 9.018348186070783
          sliceSimultaneousUse: null
          dLMaxPktSize: 9
          sST: 254
          uLLatency: 6.84685269835264
          positioning:
            predictionfrequency: null
            accuracy: 8.762042
            availability:
            - CIDE-CID
            - CIDE-CID
          dLThptPerUE:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            guaThpt: 5.637377
            maxThpt: 2.302136
          uEMobilityLevel: null
          uLThptPerUE:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            guaThpt: 5.637377
            maxThpt: 2.302136
          delayTolerance:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            support: null
          termDensity:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            density: 6
          maxNumberofUEs: 7
          uLDeterministicComm:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            periodicityList:
            - 1
            - 1
            availability: null
          dLDeterministicComm:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            periodicityList:
            - 1
            - 1
            availability: null
          dLLatency: 1.4894159098541704
          dLThptPerSliceSubnet:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            guaThpt: 5.637377
            maxThpt: 2.302136
          uLMaxPktSize: 6
          nROperatingBands: nROperatingBands
          coverageAreaTAList:
          - null
          - null
          activityFactor: 1
          resourceSharingLevel: null
        serviceProfileId: serviceProfileId
        plmnInfoList:
        - snssai:
            sd: sd
            sst: 20
          plmnId:
            mnc: mnc
            mcc: mcc
        - snssai:
            sd: sd
            sst: 20
          plmnId:
            mnc: mnc
            mcc: mcc
        cNSliceSubnetProfile:
          synchronicity:
            accuracy: 2.027123
            availability: null
          maxNumberOfPDUSessions: 7
          uLThptPerSliceSubnet:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            guaThpt: 5.637377
            maxThpt: 2.302136
          delayTolerance:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            support: null
          maxNumberofUEs: 6
          survivalTime: 1.0246457001441578
          reliability: 4.145608029883936
          energyEfficiency: 7.386281948385884
          sliceSimultaneousUse: null
          uLDeterministicComm:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            periodicityList:
            - 1
            - 1
            availability: null
          dLDeterministicComm:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            periodicityList:
            - 1
            - 1
            availability: null
          dLLatency: 1.4658129805029452
          dLMaxPktSize: 9
          uLLatency: 5.962133916683182
          dLThptPerSliceSubnet:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            guaThpt: 5.637377
            maxThpt: 2.302136
          n6Protection:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            secFuncList:
            - secRules:
              - secRules
              - secRules
              secFunId: secFunId
              secFunType: secFunType
            - secRules:
              - secRules
              - secRules
              secFunId: secFunId
              secFunType: secFunType
          uLMaxPktSize: 3
          dLThptPerUE:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            guaThpt: 5.637377
            maxThpt: 2.302136
          uLThptPerUE:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            guaThpt: 5.637377
            maxThpt: 2.302136
          nssaaSupport:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            support: null
          coverageAreaTAList:
          - null
          - null
          resourceSharingLevel: null
        topSliceSubnetProfile:
          synchronicity:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            accuracy: 6.704019
            availability: null
          maxNumberOfPDUSessions: 5
          uLThptPerSliceSubnet:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            guaThpt: 5.637377
            maxThpt: 2.302136
          survivalTime: 6.519180951018382
          reliability: 0.8851374739011653
          uESpeed: 7
          energyEfficiency:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            performance: null
          sliceSimultaneousUse: null
          dLMaxPktSize: 6
          sST: 179
          uLLatency: 1
          positioning:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            predictionfrequency: null
            accuracy: 3.3531933
            availability:
            - CIDE-CID
            - CIDE-CID
          dLThptPerUE:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            guaThpt: 5.637377
            maxThpt: 2.302136
          uEMobilityLevel: null
          uLThptPerUE:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            guaThpt: 5.637377
            maxThpt: 2.302136
          delayTolerance:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            support: null
          termDensity:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            density: 6
          maxNumberofUEs: 2
          uLDeterministicComm:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            periodicityList:
            - 1
            - 1
            availability: null
          dLDeterministicComm:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            periodicityList:
            - 1
            - 1
            availability: null
          dLLatency: 6
          dLThptPerSliceSubnet:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            guaThpt: 5.637377
            maxThpt: 2.302136
          n6Protection:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            secFuncList:
            - secRules:
              - secRules
              - secRules
              secFunId: secFunId
              secFunType: secFunType
            - secRules:
              - secRules
              - secRules
              secFunId: secFunId
              secFunType: secFunType
          uLMaxPktSize: 6
          nROperatingBands: nROperatingBands
          nssaaSupport:
            servAttrCom:
              tagging:
              - PERFORMANCE
              - PERFORMANCE
              exposure: null
              category: null
            support: null
          coverageAreaTAList:
          - null
          - null
          activityFactor: 3
          resourceSharingLevel: null
      properties:
        serviceProfileId:
          title: serviceProfileId
          type: string
        plmnInfoList:
          items:
            $ref: '#/components/schemas/PlmnInfo'
          title: plmnInfoList
          type: array
        cNSliceSubnetProfile:
          $ref: '#/components/schemas/CNSliceSubnetProfile'
        rANSliceSubnetProfile:
          $ref: '#/components/schemas/RANSliceSubnetProfile'
        topSliceSubnetProfile:
          $ref: '#/components/schemas/TopSliceSubnetProfile'
      title: SliceProfile
      type: object
    CNSliceSubnetProfile:
      example:
        synchronicity:
          accuracy: 2.027123
          availability: null
        maxNumberOfPDUSessions: 7
        uLThptPerSliceSubnet:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          guaThpt: 5.637377
          maxThpt: 2.302136
        delayTolerance:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          support: null
        maxNumberofUEs: 6
        survivalTime: 1.0246457001441578
        reliability: 4.145608029883936
        energyEfficiency: 7.386281948385884
        sliceSimultaneousUse: null
        uLDeterministicComm:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          periodicityList:
          - 1
          - 1
          availability: null
        dLDeterministicComm:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          periodicityList:
          - 1
          - 1
          availability: null
        dLLatency: 1.4658129805029452
        dLMaxPktSize: 9
        uLLatency: 5.962133916683182
        dLThptPerSliceSubnet:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          guaThpt: 5.637377
          maxThpt: 2.302136
        n6Protection:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          secFuncList:
          - secRules:
            - secRules
            - secRules
            secFunId: secFunId
            secFunType: secFunType
          - secRules:
            - secRules
            - secRules
            secFunId: secFunId
            secFunType: secFunType
        uLMaxPktSize: 3
        dLThptPerUE:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          guaThpt: 5.637377
          maxThpt: 2.302136
        uLThptPerUE:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          guaThpt: 5.637377
          maxThpt: 2.302136
        nssaaSupport:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          support: null
        coverageAreaTAList:
        - null
        - null
        resourceSharingLevel: null
      properties:
        maxNumberofUEs:
          title: maxNumberofUEs
          type: integer
        dLLatency:
          title: dLLatency
          type: number
        uLLatency:
          title: uLLatency
          type: number
        dLThptPerSliceSubnet:
          $ref: '#/components/schemas/XLThpt'
        dLThptPerUE:
          $ref: '#/components/schemas/XLThpt'
        uLThptPerSliceSubnet:
          $ref: '#/components/schemas/XLThpt'
        uLThptPerUE:
          $ref: '#/components/schemas/XLThpt'
        maxNumberOfPDUSessions:
          title: maxNumberOfPDUSessions
          type: integer
        coverageAreaTAList:
          items:
            $ref: '#/components/schemas/NrTac'
          title: NrTacList
          type: array
        resourceSharingLevel:
          $ref: '#/components/schemas/SharingLevel'
        dLMaxPktSize:
          title: dLMaxPktSize
          type: integer
        uLMaxPktSize:
          title: uLMaxPktSize
          type: integer
        delayTolerance:
          $ref: '#/components/schemas/DelayTolerance'
        synchronicity:
          $ref: '#/components/schemas/SynchronicityRANSubnet'
        sliceSimultaneousUse:
          $ref: '#/components/schemas/SliceSimultaneousUse'
        reliability:
          title: reliability
          type: number
        energyEfficiency:
          title: energyEfficiency
          type: number
        dLDeterministicComm:
          $ref: '#/components/schemas/DeterministicComm'
        uLDeterministicComm:
          $ref: '#/components/schemas/DeterministicComm'
        survivalTime:
          title: survivalTime
          type: number
        nssaaSupport:
          $ref: '#/components/schemas/NSSAASupport'
        n6Protection:
          $ref: '#/components/schemas/N6Protection'
      title: CNSliceSubnetProfile
      type: object
    XLThpt:
      example:
        servAttrCom:
          tagging:
          - PERFORMANCE
          - PERFORMANCE
          exposure: null
          category: null
        guaThpt: 5.637377
        maxThpt: 2.302136
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        guaThpt:
          format: float
          title: Float
          type: number
        maxThpt:
          format: float
          title: Float
          type: number
      title: XLThpt
      type: object
    ServAttrCom:
      example:
        tagging:
        - PERFORMANCE
        - PERFORMANCE
        exposure: null
        category: null
      properties:
        category:
          $ref: '#/components/schemas/Category'
        tagging:
          items:
            enum:
            - PERFORMANCE
            - FUNCTION
            - OPERATION
            type: string
          title: Tagging
          type: array
        exposure:
          $ref: '#/components/schemas/Exposure'
      title: ServAttrCom
      type: object
    Category:
      enum:
      - CHARACTER
      - SCALABILITY
      title: Category
      type: string
    Tagging:
      items:
        enum:
        - PERFORMANCE
        - FUNCTION
        - OPERATION
        type: string
      title: Tagging
      type: array
    Exposure:
      enum:
      - API
      - KPI
      title: Exposure
      type: string
    Float:
      format: float
      title: Float
      type: number
    SharingLevel:
      enum:
      - SHARED
      - NON-SHARED
      title: SharingLevel
      type: string
    DelayTolerance:
      example:
        servAttrCom:
          tagging:
          - PERFORMANCE
          - PERFORMANCE
          exposure: null
          category: null
        support: null
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        support:
          $ref: '#/components/schemas/Support'
      title: DelayTolerance
      type: object
    Support:
      enum:
      - NOT SUPPORTED
      - SUPPORTED
      title: Support
      type: string
    SynchronicityRANSubnet:
      example:
        accuracy: 2.027123
        availability: null
      properties:
        availability:
          $ref: '#/components/schemas/SynAvailability'
        accuracy:
          format: float
          title: Float
          type: number
      title: SynchronicityRANSubnet
      type: object
    SynAvailability:
      enum:
      - NOT SUPPORTED
      - BETWEEN BS AND UE
      - BETWEEN BS AND UE & UE AND UE
      title: SynAvailability
      type: string
    SliceSimultaneousUse:
      enum:
      - ZERO
      - ONE
      - TWO
      - THREE
      - FOUR
      title: SliceSimultaneousUse
      type: string
    DeterministicComm:
      example:
        servAttrCom:
          tagging:
          - PERFORMANCE
          - PERFORMANCE
          exposure: null
          category: null
        periodicityList:
        - 1
        - 1
        availability: null
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        availability:
          $ref: '#/components/schemas/Support'
        periodicityList:
          items:
            type: integer
          title: periodicityList
          type: array
      title: DeterministicComm
      type: object
    NSSAASupport:
      example:
        servAttrCom:
          tagging:
          - PERFORMANCE
          - PERFORMANCE
          exposure: null
          category: null
        support: null
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        support:
          $ref: '#/components/schemas/Support'
      title: NSSAASupport
      type: object
    N6Protection:
      example:
        servAttrCom:
          tagging:
          - PERFORMANCE
          - PERFORMANCE
          exposure: null
          category: null
        secFuncList:
        - secRules:
          - secRules
          - secRules
          secFunId: secFunId
          secFunType: secFunType
        - secRules:
          - secRules
          - secRules
          secFunId: secFunId
          secFunType: secFunType
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        secFuncList:
          items:
            $ref: '#/components/schemas/SecFunc'
          title: secFuncList
          type: array
      title: N6Protection
      type: object
    SecFunc:
      example:
        secRules:
        - secRules
        - secRules
        secFunId: secFunId
        secFunType: secFunType
      properties:
        secFunId:
          title: secFunId
          type: string
        secFunType:
          title: secFunType
          type: string
        secRules:
          items:
            type: string
          title: secRules
          type: array
      title: SecFunc
      type: object
    RANSliceSubnetProfile:
      example:
        synchronicity:
          accuracy: 2.027123
          availability: null
        uLThptPerSliceSubnet:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          guaThpt: 5.637377
          maxThpt: 2.302136
        survivalTime: 3.5571952270680973
        reliability: 5.025004791520295
        uESpeed: 4
        energyEfficiency: 9.018348186070783
        sliceSimultaneousUse: null
        dLMaxPktSize: 9
        sST: 254
        uLLatency: 6.84685269835264
        positioning:
          predictionfrequency: null
          accuracy: 8.762042
          availability:
          - CIDE-CID
          - CIDE-CID
        dLThptPerUE:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          guaThpt: 5.637377
          maxThpt: 2.302136
        uEMobilityLevel: null
        uLThptPerUE:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          guaThpt: 5.637377
          maxThpt: 2.302136
        delayTolerance:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          support: null
        termDensity:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          density: 6
        maxNumberofUEs: 7
        uLDeterministicComm:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          periodicityList:
          - 1
          - 1
          availability: null
        dLDeterministicComm:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          periodicityList:
          - 1
          - 1
          availability: null
        dLLatency: 1.4894159098541704
        dLThptPerSliceSubnet:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          guaThpt: 5.637377
          maxThpt: 2.302136
        uLMaxPktSize: 6
        nROperatingBands: nROperatingBands
        coverageAreaTAList:
        - null
        - null
        activityFactor: 1
        resourceSharingLevel: null
      properties:
        coverageAreaTAList:
          items:
            $ref: '#/components/schemas/NrTac'
          title: NrTacList
          type: array
        dLLatency:
          title: dLLatency
          type: number
        uLLatency:
          title: uLLatency
          type: number
        uEMobilityLevel:
          $ref: '#/components/schemas/MobilityLevel'
        resourceSharingLevel:
          $ref: '#/components/schemas/SharingLevel'
        maxNumberofUEs:
          title: maxNumberofUEs
          type: integer
        activityFactor:
          title: activityFactor
          type: integer
        dLThptPerSliceSubnet:
          $ref: '#/components/schemas/XLThpt'
        dLThptPerUE:
          $ref: '#/components/schemas/XLThpt'
        uLThptPerSliceSubnet:
          $ref: '#/components/schemas/XLThpt'
        uLThptPerUE:
          $ref: '#/components/schemas/XLThpt'
        uESpeed:
          title: uESpeed
          type: integer
        reliability:
          title: reliability
          type: number
        sST:
          maximum: 255
          title: Sst
          type: integer
        dLMaxPktSize:
          title: dLMaxPktSize
          type: integer
        uLMaxPktSize:
          title: uLMaxPktSize
          type: integer
        nROperatingBands:
          title: nROperatingBands
          type: string
        delayTolerance:
          $ref: '#/components/schemas/DelayTolerance'
        positioning:
          $ref: '#/components/schemas/PositioningRANSubnet'
        sliceSimultaneousUse:
          $ref: '#/components/schemas/SliceSimultaneousUse'
        energyEfficiency:
          title: energyEfficiency
          type: number
        termDensity:
          $ref: '#/components/schemas/TermDensity'
        survivalTime:
          title: survivalTime
          type: number
        synchronicity:
          $ref: '#/components/schemas/SynchronicityRANSubnet'
        dLDeterministicComm:
          $ref: '#/components/schemas/DeterministicComm'
        uLDeterministicComm:
          $ref: '#/components/schemas/DeterministicComm'
      title: RANSliceSubnetProfile
      type: object
    MobilityLevel:
      enum:
      - STATIONARY
      - NOMADIC
      - RESTRICTED MOBILITY
      - FULLY MOBILITY
      title: MobilityLevel
      type: string
    PositioningRANSubnet:
      example:
        predictionfrequency: null
        accuracy: 8.762042
        availability:
        - CIDE-CID
        - CIDE-CID
      properties:
        availability:
          items:
            enum:
            - CIDE-CID
            - OTDOA
            - RF FINGERPRINTING
            - AECID
            - HYBRID POSITIONING
            - NET-RTK
            type: string
          title: PositioningAvailability
          type: array
        predictionfrequency:
          $ref: '#/components/schemas/Predictionfrequency'
        accuracy:
          format: float
          title: Float
          type: number
      title: PositioningRANSubnet
      type: object
    PositioningAvailability:
      items:
        enum:
        - CIDE-CID
        - OTDOA
        - RF FINGERPRINTING
        - AECID
        - HYBRID POSITIONING
        - NET-RTK
        type: string
      title: PositioningAvailability
      type: array
    Predictionfrequency:
      enum:
      - PERSEC
      - PERMIN
      - PERHOUR
      title: Predictionfrequency
      type: string
    TermDensity:
      example:
        servAttrCom:
          tagging:
          - PERFORMANCE
          - PERFORMANCE
          exposure: null
          category: null
        density: 6
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        density:
          title: density
          type: integer
      title: TermDensity
      type: object
    TopSliceSubnetProfile:
      example:
        synchronicity:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          accuracy: 6.704019
          availability: null
        maxNumberOfPDUSessions: 5
        uLThptPerSliceSubnet:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          guaThpt: 5.637377
          maxThpt: 2.302136
        survivalTime: 6.519180951018382
        reliability: 0.8851374739011653
        uESpeed: 7
        energyEfficiency:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          performance: null
        sliceSimultaneousUse: null
        dLMaxPktSize: 6
        sST: 179
        uLLatency: 1
        positioning:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          predictionfrequency: null
          accuracy: 3.3531933
          availability:
          - CIDE-CID
          - CIDE-CID
        dLThptPerUE:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          guaThpt: 5.637377
          maxThpt: 2.302136
        uEMobilityLevel: null
        uLThptPerUE:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          guaThpt: 5.637377
          maxThpt: 2.302136
        delayTolerance:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          support: null
        termDensity:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          density: 6
        maxNumberofUEs: 2
        uLDeterministicComm:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          periodicityList:
          - 1
          - 1
          availability: null
        dLDeterministicComm:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          periodicityList:
          - 1
          - 1
          availability: null
        dLLatency: 6
        dLThptPerSliceSubnet:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          guaThpt: 5.637377
          maxThpt: 2.302136
        n6Protection:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          secFuncList:
          - secRules:
            - secRules
            - secRules
            secFunId: secFunId
            secFunType: secFunType
          - secRules:
            - secRules
            - secRules
            secFunId: secFunId
            secFunType: secFunType
        uLMaxPktSize: 6
        nROperatingBands: nROperatingBands
        nssaaSupport:
          servAttrCom:
            tagging:
            - PERFORMANCE
            - PERFORMANCE
            exposure: null
            category: null
          support: null
        coverageAreaTAList:
        - null
        - null
        activityFactor: 3
        resourceSharingLevel: null
      properties:
        dLLatency:
          title: dLLatency
          type: integer
        uLLatency:
          title: uLLatency
          type: integer
        maxNumberofUEs:
          title: maxNumberofUEs
          type: integer
        dLThptPerSliceSubnet:
          $ref: '#/components/schemas/XLThpt'
        dLThptPerUE:
          $ref: '#/components/schemas/XLThpt'
        uLThptPerSliceSubnet:
          $ref: '#/components/schemas/XLThpt'
        uLThptPerUE:
          $ref: '#/components/schemas/XLThpt'
        dLMaxPktSize:
          title: dLMaxPktSize
          type: integer
        uLMaxPktSize:
          title: uLMaxPktSize
          type: integer
        maxNumberOfPDUSessions:
          title: maxNumberOfPDUSessions
          type: integer
        nROperatingBands:
          title: nROperatingBands
          type: string
        sliceSimultaneousUse:
          $ref: '#/components/schemas/SliceSimultaneousUse'
        energyEfficiency:
          $ref: '#/components/schemas/EnergyEfficiency'
        synchronicity:
          $ref: '#/components/schemas/Synchronicity'
        delayTolerance:
          $ref: '#/components/schemas/DelayTolerance'
        positioning:
          $ref: '#/components/schemas/Positioning'
        termDensity:
          $ref: '#/components/schemas/TermDensity'
        activityFactor:
          title: activityFactor
          type: integer
        coverageAreaTAList:
          items:
            $ref: '#/components/schemas/NrTac'
          title: NrTacList
          type: array
        resourceSharingLevel:
          $ref: '#/components/schemas/SharingLevel'
        uEMobilityLevel:
          $ref: '#/components/schemas/MobilityLevel'
        uESpeed:
          title: uESpeed
          type: integer
        reliability:
          title: reliability
          type: number
        sST:
          maximum: 255
          title: Sst
          type: integer
        dLDeterministicComm:
          $ref: '#/components/schemas/DeterministicComm'
        uLDeterministicComm:
          $ref: '#/components/schemas/DeterministicComm'
        survivalTime:
          title: survivalTime
          type: number
        nssaaSupport:
          $ref: '#/components/schemas/NSSAASupport'
        n6Protection:
          $ref: '#/components/schemas/N6Protection'
      title: TopSliceSubnetProfile
      type: object
    EnergyEfficiency:
      example:
        servAttrCom:
          tagging:
          - PERFORMANCE
          - PERFORMANCE
          exposure: null
          category: null
        performance: null
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        performance:
          $ref: '#/components/schemas/EEPerfReq'
      title: EnergyEfficiency
      type: object
    EEPerfReq:
      oneOf:
      - $ref: '#/components/schemas/EmbbEEPerfReq'
      - $ref: '#/components/schemas/UrllcEEPerfReq'
      - $ref: '#/components/schemas/MIoTEEPerfReq'
      title: EEPerfReq
    EmbbEEPerfReq:
      properties:
        kpiType:
          enum:
          - NUMOFBITS
          - NUMOFBITS_RANBASED
          title: kpiType
          type: string
        req:
          title: req
          type: number
      title: EmbbEEPerfReq
      type: object
    UrllcEEPerfReq:
      properties:
        kpiType:
          enum:
          - INVOFLATENCY
          - NUMOFBITS_MULTIPLIED_INVOFLATENCY
          title: kpiType
          type: string
        req:
          title: req
          type: number
      title: UrllcEEPerfReq
      type: object
    MIoTEEPerfReq:
      properties:
        kpiType:
          enum:
          - MAXREGSUBS
          - MEANACTIVEUES
          title: kpiType
          type: string
        req:
          title: req
          type: number
      title: MIoTEEPerfReq
      type: object
    Synchronicity:
      example:
        servAttrCom:
          tagging:
          - PERFORMANCE
          - PERFORMANCE
          exposure: null
          category: null
        accuracy: 6.704019
        availability: null
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        availability:
          $ref: '#/components/schemas/SynAvailability'
        accuracy:
          format: float
          title: Float
          type: number
      title: Synchronicity
      type: object
    Positioning:
      example:
        servAttrCom:
          tagging:
          - PERFORMANCE
          - PERFORMANCE
          exposure: null
          category: null
        predictionfrequency: null
        accuracy: 3.3531933
        availability:
        - CIDE-CID
        - CIDE-CID
      properties:
        servAttrCom:
          $ref: '#/components/schemas/ServAttrCom'
        availability:
          items:
            enum:
            - CIDE-CID
            - OTDOA
            - RF FINGERPRINTING
            - AECID
            - HYBRID POSITIONING
            - NET-RTK
            type: string
          title: PositioningAvailability
          type: array
        predictionfrequency:
          $ref: '#/components/schemas/Predictionfrequency'
        accuracy:
          format: float
          title: Float
          type: number
      title: Positioning
      type: object
    ErrorResponse:
      description: Default schema for the response message body in case the request
        is not successful.
      properties:
        error:
          $ref: '#/components/schemas/ErrorResponse_error'
      title: ErrorResponse
      type: object
    Filter:
      description: The filter format shall be compliant to XPath 1.0.
      type: string
    PlmnInfoList:
      items:
        $ref: '#/components/schemas/PlmnInfo'
      title: plmnInfoList
      type: array
    PlmnInfo:
      example:
        snssai:
          sd: sd
          sst: 20
        plmnId:
          mnc: mnc
          mcc: mcc
      properties:
        plmnId:
          $ref: '#/components/schemas/PlmnId'
        snssai:
          $ref: '#/components/schemas/Snssai'
      title: PlmnInfo
      type: object
    PlmnId:
      example:
        mnc: mnc
        mcc: mcc
      properties:
        mcc:
          pattern: "^[0-9]{3}$"
          title: Mcc
          type: string
        mnc:
          pattern: "[0-9]{3}|[0-9]{2}"
          title: Mnc
          type: string
      title: PlmnId
      type: object
    Mnc:
      pattern: "[0-9]{3}|[0-9]{2}"
      title: Mnc
      type: string
    Snssai:
      example:
        sd: sd
        sst: 20
      properties:
        sst:
          maximum: 255
          title: Sst
          type: integer
        sd:
          title: sd
          type: string
      title: Snssai
      type: object
    Sst:
      maximum: 255
      title: Sst
      type: integer
    NrTacList:
      items:
        $ref: '#/components/schemas/NrTac'
      title: NrTacList
      type: array
    NrTac:
      maximum: 16777215
      title: NrTac
      type: integer
    Mcc:
      pattern: "^[0-9]{3}$"
      title: Mcc
      type: string
    ErrorResponse_error:
      properties:
        errorInfo:
          title: errorInfo
          type: string
      title: ErrorResponse_error
      type: object
